version: '3'
services:
    maria_db:
        container_name: "maria.db.public"
        image: "evrinoma/db.maria"
        hostname: "maria.db.public"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            - virt

    php74_clean:
        container_name: "php74.clean.public"
        image: "evrinoma/php74"
        hostname: "php74.clean.public"
        environment:
            - ENGINE=nginx
            - DEPLOY=yes
            - SYMFONY=yes
            - MODE=dev
            - _NODEJS=10
            - git_clone_link=https://github.com/evrinoma/limangorec
            - git_clone_dir=/opt/WWW/container.ite-ng.ru/projects/nginx/
            - web_dir=/opt/WWW/container.ite-ng.ru/projects/nginx/limangorec
            - web_server=php74.clean.public
            - web_alias=clean
            - console=cd /opt/WWW/container.ite-ng.ru/projects/nginx/limangorec && composer install && /usr/bin/php vendor/phpunit/phpunit/phpunit --bootstrap /opt/WWW/container.ite-ng.ru/projects/nginx/limangorec/src/Tests/bootstrap.php --configuration phpunit.xml.dist /opt/WWW/container.ite-ng.ru/projects/nginx/limangorec/src/Tests/Command/ > /tmp/unit.txt
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            - virt

networks:
    virt:
        driver: bridge
        ipam:
            driver: default
